# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.7.1
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: check-coverage
        name: Check Coverage
        entry: bash -c "coverage run --source=. -m unittest discover -s tests && coverage report -m --fail-under=60"
        language: system
