# .pre-commit-config.yaml
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "latest"
    hooks:
      - id: ruff
        args: ["--fix", "--select", "F,E,W,B,I,S"]
  - repo: https://github.com/psf/black
    rev: "stable"
    hooks:
      - id: black
