# pyproject.toml

[build-system]
requires = ["setuptools", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ReadmeGenie"  # Name of your project on PyPI
description = "A tool to generate README files effortlessly"
readme = "README.md"  # Optional: Path to README file
license = { file = "LICENSE" }
authors = [
    { name = "Henrique Sagara", email = "henrique.sagara@hotmail.com" }
]
dependencies = [
    "cohere>=5.11.0,<6.0.0",
    "colorama>=0.4.6",
    "groq>=0.11.0",
    "python-dotenv>=1.0.1",
    "toml>=0.10.2"
]
[project.optional-dependencies]
dev = [
    "black>=23.3.0",
    "ruff>=0.0.261",
    "pre-commit",
    "coverage"
]

dynamic = ["version"]  # Keep version and classifiers dynamic

requires-python = ">=3.7"  # Declare this statically (remove it from dynamic)

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.setuptools_scm]
version_scheme = "post-release"

[project.urls]
Homepage = "https://github.com/HTSagara/readme_genie"
Documentation = "https://github.com/HTSagara/readme_genie/blob/main/README.md"

# Set up black as formatter
[tool.black]
line-length = 79
target-version = ["py311"]

# Set up ruff as linter only
[tool.ruff]
# Exclude directories that don’t need linting (e.g., virtual environments)
exclude = [
    "venv/",
    "__pycache__/"
]
fix = true


# Enable specific linting rules
select = ["F", "E", "W", "B", "I", "S"]  # Example codes: F=flake8, E=errors, W=warnings, B=bugbear, I=import, S=safety
# Exclude Black-compatible rules to avoid conflicts with Black's formatting.
ignore = ["E501", "E203", "E231"]  # Exclude Black-incompatible style issues

[tool.coverage.run]
source = ["."]
branch = true
omit = ["tests/*"]


[tool.pytest.ini_options]
pythonpath = ["src"]
